package io.scalaland.chimney.internal.compiletime

/** Compatibility shims for macro-commons' `Type.Option`/`Type.Either`/`Expr.Option`/`Expr.Either`/`Expr.Function1`
  * modules (and the related `TypeOps.isOption/isEither/isLeft/isRight` + expr ops), which have no 1:1 Hearth
  * counterpart and are needed by the ported rules.
  *
  * Naming: we cannot add members to Hearth's `Type`/`Expr` modules, so the macro-commons `Type.X`/`Expr.X` call sites
  * are renamed mechanically to `ScalaType.X`/`ScalaExpr.X`.
  *
  * Implementation notes:
  *   - type-constructor modules are built with `Type.CtorN.fromUntyped` (over the cross-quoted `Type.CtorN.of`
  *     constructor) - `fromUntyped`'s `unapply` is `baseType`-aware, which matches macro-commons' `Ctor` matching
  *     semantics (see [[derivation.transformer.integrations.OptionalValues]] for the same pattern and rationale),
  *   - like macro-commons' `Type.Implicits`, the implicit `Type` providers live in an explicitly-imported
  *     [[ScalaType.Implicits]] object (NOT ambient in the cake) to avoid clashing with locally-defined implicit `Type`
  *     vals,
  *   - all `Expr` helpers use cross-quotes in methods with their own `[X: Type]` parameters (the helper-method pattern
  *     required by Scala 2 cross-quotes),
  *   - GOTCHA (Scala 2): the code generated by `Type.CtorN.of`/`Type.of` references bare `Some`/`None` - it must NOT
  *     expand inside a scope that shadows them (e.g. inside `ScalaType.Option`, which defines members named `Some` and
  *     `None`). All macro expansions are therefore hoisted to `private lazy val`s at the (unshadowed) trait level.
  */
private[compiletime] trait ScalaStdCompat { this: hearth.MacroCommons =>

  // All cross-quotes expansions hoisted here - see the GOTCHA in the trait's ScalaDoc.
  private lazy val optionCtor: Type.Ctor1[scala.Option] =
    Type.Ctor1.fromUntyped[scala.Option](Type.Ctor1.of[scala.Option].asUntyped)
  private lazy val someCtor: Type.Ctor1[scala.Some] =
    Type.Ctor1.fromUntyped[scala.Some](Type.Ctor1.of[scala.Some].asUntyped)
  private lazy val noneType: Type[scala.None.type] = Type.of[scala.None.type]
  private lazy val optionOfAny: Type[scala.Option[Any]] = Type.of[scala.Option[Any]]
  private lazy val eitherCtor: Type.Ctor2[scala.Either] =
    Type.Ctor2.fromUntyped[scala.Either](Type.Ctor2.of[scala.Either].asUntyped)
  private lazy val leftCtor: Type.Ctor2[scala.Left] =
    Type.Ctor2.fromUntyped[scala.Left](Type.Ctor2.of[scala.Left].asUntyped)
  private lazy val rightCtor: Type.Ctor2[scala.Right] =
    Type.Ctor2.fromUntyped[scala.Right](Type.Ctor2.of[scala.Right].asUntyped)
  private lazy val eitherOfAny: Type[scala.Either[Any, Any]] = Type.of[scala.Either[Any, Any]]
  private lazy val leftOfAny: Type[scala.Left[Any, Any]] = Type.of[scala.Left[Any, Any]]
  private lazy val rightOfAny: Type[scala.Right[Any, Any]] = Type.of[scala.Right[Any, Any]]
  private lazy val tuple2Ctor: Type.Ctor2[scala.Tuple2] =
    Type.Ctor2.fromUntyped[scala.Tuple2](Type.Ctor2.of[scala.Tuple2].asUntyped)
  private lazy val iteratorCtor: Type.Ctor1[scala.collection.Iterator] =
    Type.Ctor1.fromUntyped[scala.collection.Iterator](Type.Ctor1.of[scala.collection.Iterator].asUntyped)
  private lazy val factoryCtor: Type.Ctor2[scala.collection.Factory] =
    Type.Ctor2.fromUntyped[scala.collection.Factory](Type.Ctor2.of[scala.collection.Factory].asUntyped)
  private lazy val anyType: Type[scala.Any] = Type.of[scala.Any]
  private lazy val intType: Type[scala.Int] = Type.of[scala.Int]
  private lazy val unitType: Type[scala.Unit] = Type.of[scala.Unit]
  private lazy val nullType: Type[scala.Null] = Type.of[scala.Null]
  private lazy val nullExprCompat: Expr[scala.Null] = Expr.NullExprCodec.toExpr(null)

  // Cross-quotes helper defs for the `ScalaExpr.Iterator`/`Tuple2`/`Function2` modules below - hoisted to the
  // (unshadowed) trait level like everything above (inside e.g. `object Iterator` the bare name `Iterator` that the
  // generated code may reference would resolve to the module itself - the same trap as GOTCHA above).
  private def iteratorMapCompat[A: Type, B: Type](
      it: Expr[scala.collection.Iterator[A]],
      f: Expr[A => B]
  ): Expr[scala.collection.Iterator[B]] = Expr.quote {
    Expr.splice(it).map(Expr.splice(f))
  }
  private def iteratorToCompat[A: Type, C: Type](
      it: Expr[scala.collection.Iterator[A]],
      factory: Expr[scala.collection.Factory[A, C]]
  ): Expr[C] = Expr.quote {
    Expr.splice(it).to(Expr.splice(factory))
  }
  private def iteratorZipWithIndexCompat[A: Type](
      it: Expr[scala.collection.Iterator[A]]
  ): Expr[scala.collection.Iterator[(A, scala.Int)]] = Expr.quote {
    Expr.splice(it).zipWithIndex
  }
  private def iteratorConcatCompat[A: Type](
      it: Expr[scala.collection.Iterator[A]],
      it2: Expr[scala.collection.Iterator[A]]
  ): Expr[scala.collection.Iterator[A]] = Expr.quote {
    Expr.splice(it) ++ Expr.splice(it2)
  }
  private def tuple2ApplyCompat[A: Type, B: Type](a: Expr[A], b: Expr[B]): Expr[(A, B)] = Expr.quote {
    (Expr.splice(a), Expr.splice(b))
  }
  private def function2TupledCompat[A: Type, B: Type, C: Type](f: Expr[(A, B) => C]): Expr[((A, B)) => C] =
    Expr.quote {
      Expr.splice(f).tupled
    }

  protected object ScalaType {

    /** macro-commons `Type.Option` (+ `.Some`, `.None`). */
    object Option {

      def apply[A: Type]: Type[scala.Option[A]] = optionCtor[A]
      def unapply[A](A: Type[A]): scala.Option[??] = optionCtor.unapply(A)

      def OfAny: Type[scala.Option[Any]] = optionOfAny

      object Some {
        def apply[A: Type]: Type[scala.Some[A]] = someCtor[A]
        def unapply[A](A: Type[A]): scala.Option[??] = someCtor.unapply(A)
      }

      def None: Type[scala.None.type] = noneType
    }

    /** macro-commons `Type.Either` (+ `.Left`, `.Right`). */
    object Either {

      def apply[L: Type, R: Type]: Type[scala.Either[L, R]] = eitherCtor[L, R]
      def unapply[A](A: Type[A]): scala.Option[(??, ??)] = eitherCtor.unapply(A)

      def OfAny: Type[scala.Either[Any, Any]] = eitherOfAny

      object Left {
        def apply[L: Type, R: Type]: Type[scala.Left[L, R]] = leftCtor[L, R]
        def unapply[A](A: Type[A]): scala.Option[(??, ??)] = leftCtor.unapply(A)

        def OfAny: Type[scala.Left[Any, Any]] = leftOfAny
      }

      object Right {
        def apply[L: Type, R: Type]: Type[scala.Right[L, R]] = rightCtor[L, R]
        def unapply[A](A: Type[A]): scala.Option[(??, ??)] = rightCtor.unapply(A)

        def OfAny: Type[scala.Right[Any, Any]] = rightOfAny
      }
    }

    /** macro-commons `Type.Tuple2`. */
    object Tuple2 {

      def apply[A: Type, B: Type]: Type[(A, B)] = tuple2Ctor[A, B]
      def unapply[A](A: Type[A]): scala.Option[(??, ??)] = tuple2Ctor.unapply(A)
    }

    /** macro-commons `Type.Iterator`. */
    object Iterator {

      def apply[A: Type]: Type[scala.collection.Iterator[A]] = iteratorCtor[A]
      def unapply[A](A: Type[A]): scala.Option[??] = iteratorCtor.unapply(A)
    }

    /** macro-commons `Type.Factory`. */
    object Factory {

      def apply[A: Type, C: Type]: Type[scala.collection.Factory[A, C]] = factoryCtor[A, C]
    }

    /** macro-commons `Type.Implicits` subset needed by the rules (explicit import, like the original). */
    object Implicits {

      implicit def OptionType[A: Type]: Type[scala.Option[A]] = Option[A]
      implicit def SomeType[A: Type]: Type[scala.Some[A]] = Option.Some[A]
      implicit def NoneType: Type[scala.None.type] = Option.None

      implicit def EitherType[L: Type, R: Type]: Type[scala.Either[L, R]] = Either[L, R]
      implicit def LeftType[L: Type, R: Type]: Type[scala.Left[L, R]] = Either.Left[L, R]
      implicit def RightType[L: Type, R: Type]: Type[scala.Right[L, R]] = Either.Right[L, R]

      implicit def Function1Type[A: Type, B: Type]: Type[A => B] = Type.of[A => B]

      implicit def Tuple2Type[A: Type, B: Type]: Type[(A, B)] = Tuple2[A, B]
      implicit def IteratorType[A: Type]: Type[scala.collection.Iterator[A]] = Iterator[A]
      implicit def FactoryType[A: Type, C: Type]: Type[scala.collection.Factory[A, C]] = Factory[A, C]

      implicit def AnyType: Type[scala.Any] = anyType
      implicit def IntType: Type[scala.Int] = intType
      implicit def UnitType: Type[scala.Unit] = unitType
      implicit def NullType: Type[scala.Null] = nullType
    }
  }

  /** macro-commons `TypeOps.isOption/isEither/isLeft/isRight` counterparts (same `<:< F[Any, ...]` semantics). */
  implicit final protected class ScalaStdTypeOps[A](private val tpe: Type[A]) {

    def isOption: Boolean = tpe <:< ScalaType.Option.OfAny
    def isEither: Boolean = tpe <:< ScalaType.Either.OfAny
    def isLeft: Boolean = tpe <:< ScalaType.Either.Left.OfAny
    def isRight: Boolean = tpe <:< ScalaType.Either.Right.OfAny
  }

  protected object ScalaExpr {

    /** macro-commons `Expr.Option.apply`. */
    object Option {
      def apply[A: Type](value: Expr[A]): Expr[scala.Option[A]] = Expr.quote {
        scala.Option[A](Expr.splice(value))
      }
    }

    /** macro-commons `Expr.Either` (+ `.Left`, `.Right`). */
    object Either {

      def fold[L: Type, R: Type, A: Type](either: Expr[scala.Either[L, R]])(left: Expr[L => A])(
          right: Expr[R => A]
      ): Expr[A] = Expr.quote {
        Expr.splice(either).fold[A](Expr.splice(left), Expr.splice(right))
      }

      def orElse[L: Type, R: Type](
          either1: Expr[scala.Either[L, R]],
          either2: Expr[scala.Either[L, R]]
      ): Expr[scala.Either[L, R]] = Expr.quote {
        Expr.splice(either1).orElse(Expr.splice(either2))
      }

      object Left {
        def apply[L: Type, R: Type](value: Expr[L]): Expr[scala.Left[L, R]] = Expr.quote {
          scala.Left[L, R](Expr.splice(value))
        }

        def value[L: Type, R: Type](left: Expr[scala.Left[L, R]]): Expr[L] = Expr.quote {
          Expr.splice(left).value
        }
      }

      object Right {
        def apply[L: Type, R: Type](value: Expr[R]): Expr[scala.Right[L, R]] = Expr.quote {
          scala.Right[L, R](Expr.splice(value))
        }

        def value[L: Type, R: Type](right: Expr[scala.Right[L, R]]): Expr[R] = Expr.quote {
          Expr.splice(right).value
        }
      }
    }

    /** macro-commons `Expr.Function1.apply` (function application, NOT lambda creation - for the latter use
      * `LambdaBuilder`/direct cross-quotes lambdas).
      */
    object Function1 {
      def apply[A: Type, B: Type](fn: Expr[A => B])(a: Expr[A]): Expr[B] = Expr.quote {
        Expr.splice(fn).apply(Expr.splice(a))
      }
    }

    /** macro-commons `Expr.Function2.tupled` (`.instance` is replaced by `LambdaBuilder.of2`). */
    object Function2 {
      def tupled[A: Type, B: Type, C: Type](fn: Expr[(A, B) => C]): Expr[((A, B)) => C] = function2TupledCompat(fn)
    }

    /** macro-commons `Expr.Null`. */
    def Null: Expr[scala.Null] = nullExprCompat

    /** macro-commons `Expr.Tuple2.apply`. */
    object Tuple2 {
      def apply[A: Type, B: Type](a: Expr[A], b: Expr[B]): Expr[(A, B)] = tuple2ApplyCompat(a, b)
    }

    /** macro-commons `Expr.Iterator` module subset used by the rules. */
    object Iterator {
      def map[A: Type, B: Type](it: Expr[scala.collection.Iterator[A]])(
          f: Expr[A => B]
      ): Expr[scala.collection.Iterator[B]] = iteratorMapCompat(it, f)

      def to[A: Type, C: Type](it: Expr[scala.collection.Iterator[A]])(
          factory: Expr[scala.collection.Factory[A, C]]
      ): Expr[C] = iteratorToCompat(it, factory)

      def zipWithIndex[A: Type](it: Expr[scala.collection.Iterator[A]]): Expr[scala.collection.Iterator[(A, Int)]] =
        iteratorZipWithIndexCompat(it)

      def concat[A: Type](
          it: Expr[scala.collection.Iterator[A]],
          it2: Expr[scala.collection.Iterator[A]]
      ): Expr[scala.collection.Iterator[A]] = iteratorConcatCompat(it, it2)
    }
  }

  /** macro-commons `Function1Ops.apply` counterpart. */
  implicit final protected class ScalaFunction1ExprOps[A: Type, B: Type](private val fn: Expr[A => B]) {

    def apply(a: Expr[A]): Expr[B] = ScalaExpr.Function1(fn)(a)
  }

  /** macro-commons `EitherOps.fold/orElse` counterpart. */
  implicit final protected class ScalaEitherExprOps[L: Type, R: Type](private val either: Expr[scala.Either[L, R]]) {

    def fold[A: Type](left: Expr[L => A])(right: Expr[R => A]): Expr[A] = ScalaExpr.Either.fold(either)(left)(right)
    def orElse(either2: Expr[scala.Either[L, R]]): Expr[scala.Either[L, R]] = ScalaExpr.Either.orElse(either, either2)
  }

  /** macro-commons `LeftExprOps.value` counterpart. */
  implicit final protected class ScalaLeftExprOps[L: Type, R: Type](private val left: Expr[scala.Left[L, R]]) {

    def value: Expr[L] = ScalaExpr.Either.Left.value(left)
  }

  /** macro-commons `RightExprOps.value` counterpart. */
  implicit final protected class ScalaRightExprOps[L: Type, R: Type](private val right: Expr[scala.Right[L, R]]) {

    def value: Expr[R] = ScalaExpr.Either.Right.value(right)
  }

  /** macro-commons `Function2Ops.tupled` counterpart. */
  implicit final protected class ScalaFunction2ExprOps[A: Type, B: Type, C: Type](
      private val fn: Expr[(A, B) => C]
  ) {

    def tupled: Expr[((A, B)) => C] = ScalaExpr.Function2.tupled(fn)
  }

  /** macro-commons `IteratorOps` counterpart (subset used by the rules). */
  implicit final protected class ScalaIteratorExprOps[A: Type](private val it: Expr[scala.collection.Iterator[A]]) {

    def map[B: Type](f: Expr[A => B]): Expr[scala.collection.Iterator[B]] = ScalaExpr.Iterator.map(it)(f)
    def to[C: Type](factory: Expr[scala.collection.Factory[A, C]]): Expr[C] = ScalaExpr.Iterator.to(it)(factory)
    def zipWithIndex: Expr[scala.collection.Iterator[(A, Int)]] = ScalaExpr.Iterator.zipWithIndex(it)
    def concat(it2: Expr[scala.collection.Iterator[A]]): Expr[scala.collection.Iterator[A]] =
      ScalaExpr.Iterator.concat(it, it2)
  }
}
