# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: docs/mkdocs.yml
