// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.scalaland.chimney.examples.pb.addressbook

@SerialVersionUID(0L)
final case class AddressBook(
    people: _root_.scala.collection.Seq[io.scalaland.chimney.examples.pb.addressbook.Person] =
      _root_.scala.collection.Seq.empty
)
