// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.scalaland.chimney.fixtures.pb.addressbook

@SerialVersionUID(0L)
final case class PhoneNumber(
    number: _root_.scala.Predef.String = "",
    `type`: io.scalaland.chimney.fixtures.pb.addressbook.PhoneType =
      io.scalaland.chimney.fixtures.pb.addressbook.PhoneType.MOBILE
)
