// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.scalaland.chimney.fixtures.pb.addressbook

sealed trait PhoneType {
  type EnumType = PhoneType
  def isMobile: _root_.scala.Boolean = false
  def isHome: _root_.scala.Boolean = false
  def isWork: _root_.scala.Boolean = false
}

object PhoneType {

  @SerialVersionUID(0L)
  case object MOBILE extends PhoneType {
    val value = 0
    val index = 0
    val name = "MOBILE"
    override def isMobile: _root_.scala.Boolean = true
  }

  @SerialVersionUID(0L)
  case object HOME extends PhoneType {
    val value = 1
    val index = 1
    val name = "HOME"
    override def isHome: _root_.scala.Boolean = true
  }

  @SerialVersionUID(0L)
  case object WORK extends PhoneType {
    val value = 2
    val index = 2
    val name = "WORK"
    override def isWork: _root_.scala.Boolean = true
  }

  @SerialVersionUID(0L)
  final case class Unrecognized(value: _root_.scala.Int) extends PhoneType

  lazy val values = scala.collection.Seq(MOBILE, HOME, WORK)
  def fromValue(value: _root_.scala.Int): PhoneType = value match {
    case 0       => MOBILE
    case 1       => HOME
    case 2       => WORK
    case __other => Unrecognized(__other)
  }
}
