// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package io.scalaland.chimney.examples.pb.order

@SerialVersionUID(0L)
final case class Item(
    id: _root_.scala.Int = 0,
    name: _root_.scala.Predef.String = ""
)
