site_name: 'Chimney documentation'
repo_url: https://github.com/scalalandio/chimney
edit_uri: edit/master/docs/docs/
docs_dir: 'docs'
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.integrate
  font:
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/logo.svg
nav:
  - 'Welcome': 'index.md'
  - 'Quick Start': 'quickstart.md'
  - 'Supported Transformations': 'supported-transformations.md'
  - 'Supported Patching': 'supported-patching.md'
  - 'Cookbook': 'cookbook.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Under the Hood': 'under-the-hood.md'
  - 'Benchmarks': 'benchmarks.md'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - macros
  - search
copyright: |
  Copyright © 2017—2024, <a href="https://scalaland.io">Scalaland.io</a>.<br />
  Chimney is FOSS licensed under Apache 2.0<br />
  <br />
  Documentation made with <a href="https://www.mkdocs.org">MkDocs</a>, <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a> and <a href="https://mkdocs-macros-plugin.readthedocs.io/">Mkdocs-Macros</a>, hosted on <a href="https://readthedocs.org/">ReadTheDocs</a>
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scalalandio/chimney
    - icon: fontawesome/solid/book-bookmark
      link: https://index.scala-lang.org/scalalandio/chimney
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@scalaland
  scala:
    2_12: "2.12.19"
    2_13: "2.13.13"
    3:    "3.3.3"
  local:
    tag: !ENV [CI_LATEST_TAG, 'latest'] # used as git.tag fallback in Docker container
