name: Build docs

on:
  push:
    branches: [ master, scala-3 ] # TODO: remove scala-3 before merging to master
  pull_request:
    branches: [ master, scala-3 ] # TODO: remove scala-3 before merging to master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "pip install sphinx_rtd_theme"
          build-command: "sphinx-build -b html source build"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
