name: Sonatype Release

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  release-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - name: Import GPG key for signing the release
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - uses: coursier/setup-action@v1.3.9
        with:
          jvm: 'temurin:1.8.0-392'
          apps: sbt
      - name: Publish all projects
        run:  sbt ci-release
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
