name: Sonatype Release

on:
  workflow_run:
    workflows: [ 'CI build' ]
    branches: [ master ]
    types: [ completed ]

jobs:
  release-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - name: Import GPG key for signing the release
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - uses: coursier/setup-action@v1.3.0
        with:
          jvm: 'adopt:1.8.0-292'
          apps: sbt
      - name: Stage all artifacts and then release them in batch
        run:  sbt publishSigned sonatypeBundleRelease
        env:
          RELEASE: true
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
